/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyDropdown {
        /**
          * @default 'Search...'
         */
        "placeholder": string;
    }
    interface MyDropdownOption {
        /**
          * @default false
         */
        "isFocused": boolean;
        /**
          * @default false
         */
        "isSelected": boolean;
        "label"?: string;
        "select": () => Promise<void>;
        "value": string;
    }
}
export interface MyDropdownOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyDropdownOptionElement;
}
declare global {
    interface HTMLMyDropdownElement extends Components.MyDropdown, HTMLStencilElement {
    }
    var HTMLMyDropdownElement: {
        prototype: HTMLMyDropdownElement;
        new (): HTMLMyDropdownElement;
    };
    interface HTMLMyDropdownOptionElementEventMap {
        "optionSelectedToggle": { value: string; label: string };
    }
    interface HTMLMyDropdownOptionElement extends Components.MyDropdownOption, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyDropdownOptionElementEventMap>(type: K, listener: (this: HTMLMyDropdownOptionElement, ev: MyDropdownOptionCustomEvent<HTMLMyDropdownOptionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyDropdownOptionElementEventMap>(type: K, listener: (this: HTMLMyDropdownOptionElement, ev: MyDropdownOptionCustomEvent<HTMLMyDropdownOptionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyDropdownOptionElement: {
        prototype: HTMLMyDropdownOptionElement;
        new (): HTMLMyDropdownOptionElement;
    };
    interface HTMLElementTagNameMap {
        "my-dropdown": HTMLMyDropdownElement;
        "my-dropdown-option": HTMLMyDropdownOptionElement;
    }
}
declare namespace LocalJSX {
    interface MyDropdown {
        /**
          * @default 'Search...'
         */
        "placeholder"?: string;
    }
    interface MyDropdownOption {
        /**
          * @default false
         */
        "isFocused"?: boolean;
        /**
          * @default false
         */
        "isSelected"?: boolean;
        "label"?: string;
        "onOptionSelectedToggle"?: (event: MyDropdownOptionCustomEvent<{ value: string; label: string }>) => void;
        "value": string;
    }
    interface IntrinsicElements {
        "my-dropdown": MyDropdown;
        "my-dropdown-option": MyDropdownOption;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-dropdown": LocalJSX.MyDropdown & JSXBase.HTMLAttributes<HTMLMyDropdownElement>;
            "my-dropdown-option": LocalJSX.MyDropdownOption & JSXBase.HTMLAttributes<HTMLMyDropdownOptionElement>;
        }
    }
}
